# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LSWeiboSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LSWeiboSwift

pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"


end
